---
variables:
  DEBIAN_OLDSTABLE_CODE: stretch
  DEBIAN_OLDSTABLE_VERSION: 9
  DEBIAN_STABLE_CODE: buster
  DEBIAN_STABLE_VERSION: 10
  UBUNTU_OLDLTS_CODE: xenial
  UBUNTU_OLDLTS_VERSION: 1604
  MINT_OLDLTS_CODE: sara
  UBUNTU_LTS_CODE: bionic
  UBUNTU_LTS_VERSION: 1804
  MINT_LTS_CODE: tara
  UBUNTU_STABLE_CODE: eoan
  UBUNTU_STABLE_VERSION: 1910
  FEDORA_OLDSTABLE_VERSION: 30
  FEDORA_STABLE_VERSION: 31
  CENTOS_OLDSTABLE_VERSION: 7
  CENTOS_STABLE_VERSION: 8
  OPENSUSE_OLDSTABLE_VERSION: "15.0"
  OPENSUSE_STABLE_VERSION: "15.1"

stages:
- build
- sign

build:
  image: debian:stable
  stage: build
  before_script:
  - apt-get update
  - apt-get -y install --no-install-recommends devscripts equivs build-essential fakeroot rpm
  - mk-build-deps -r -i -t "apt-get -y -o Debug::pkgProblemResolver=yes --no-install-recommends"
  - mkdir -p products/deb
  - mkdir -p products/rpm
  script:
  - dpkg-buildpackage -uc -us -i -I.git -rfakeroot
  - dcmd mv ../eid-archive*changes products/deb
  - make rpms
  - cp -a /root/rpmbuild/RPMS/noarch/* products/rpm
  artifacts:
    paths:
    - products

sign-deb:
  stage: sign
  tags:
  - repobuilder
  only:
  - gitlab
  script:
  - set -e
  - if [ -z "$REPREPRO_BASE_DIR"]; then export REPREPRO_BASE_DIR=/srv/repo/reprepro; fi
  - for deb in products/deb/*.changes; do if ./scripts/deb-is-needed.pl $deb; then dcmd mv $deb /srv/repo/reprepro/incoming; fi; done
  - reprepro processincoming incoming

sign-fed:
  stage: sign
  tags:
  - repobuilder
  only:
  - gitlab
  script:
  - set -e
  - for rpm in products/rpm/*.rpm; do ./scripts/rpm-sign-and-move.pl $rpm; done
