---
variables:
  DEBIAN_OLDSTABLE_CODE: bookworm
  DEBIAN_OLDSTABLE_VERSION: 12
  BOOKWORM_FULLNAME: Debian 12 "bookworm"
  DEBIAN_STABLE_CODE: trixie
  DEBIAN_STABLE_VERSION: 13
  TRIXIE_FULLNAME: Debian 13 "trixie"
  UBUNTU_OLDLTS_CODE: jammy
  UBUNTU_OLDLTS_VERSION: 2204
  JAMMY_FULLNAME: Jammy Jellyfish
  MINT_OLDLTS_CODE: sara
  SARA_FULLNAME: Sara
  UBUNTU_LTS_CODE: noble
  UBUNTU_LTS_VERSION: 2404
  NOBLE_FULLNAME: Bionic Beaver
  MINT_LTS_CODE: vanessa
  VANESSA_FULLNAME: VANESSA
  UBUNTU_STABLE_CODE: eoan
  UBUNTU_STABLE_VERSION: 1910
  EOAN_FULLNAME: Eoan Ermine
  FEDORA_OLDSTABLE_VERSION: 30
  FEDORA_STABLE_VERSION: 31
  CENTOS_OLDSTABLE_VERSION: 7
  CENTOS_STABLE_VERSION: 8
  OPENSUSE_OLDSTABLE_VERSION: "15.0"
  OPENSUSE_STABLE_VERSION: "15.1"

stages:
- build
- sign

build:
  image: debian:stable
  stage: build
  before_script:
  - apt-get update
  - apt-get -y install --no-install-recommends devscripts equivs build-essential fakeroot rpm
  - mk-build-deps -r -i -t "apt-get -y -o Debug::pkgProblemResolver=yes --no-install-recommends"
  - mkdir -p products/deb
  - mkdir -p products/rpm
  script:
  - dpkg-buildpackage -uc -us -i -I.git -rfakeroot
  - dcmd mv ../eid-archive*changes products/deb
  - make rpms
  - cp -a /root/rpmbuild/RPMS/noarch/* products/rpm
  artifacts:
    paths:
    - products

sign-deb:
  stage: sign
  tags:
  - repobuilder
  rules:
    - when: manual
  script:
  - set -e
  - if [ -z "$REPREPRO_BASE_DIR"]; then export REPREPRO_BASE_DIR=/srv/repo/reprepro; fi
  - ./scripts/ensure-reprepro.pl
  - for deb in products/deb/*.changes; do if ./scripts/deb-is-needed.pl $deb; then dcmd mv $deb /srv/repo/reprepro/incoming; fi; done
  - reprepro processincoming incoming
  - for deb in products/deb/*.changes; do ./scripts/deb-copy-if-needed.pl $deb; done

sign-fed:
  stage: sign
  tags:
  - repobuilder
  rules:
    - when: manual
  script:
  - set -e
  - for rpm in products/rpm/*.rpm; do ./scripts/rpm-sign-and-move.pl $rpm; done
