---
include:
  - project: 'eid-mw/eid-mw'
    ref: master
    file: '/.ci/build-configs.yml'

stages:
- build
- sign

build:
  image: debian:stable
  stage: build
  before_script:
  - apt-get update
  - apt-get -y install --no-install-recommends devscripts equivs build-essential fakeroot rpm
  - mk-build-deps -r -i -t "apt-get -y -o Debug::pkgProblemResolver=yes --no-install-recommends"
  - mkdir -p products/deb
  - mkdir -p products/rpm
  script:
  - dpkg-buildpackage -uc -us -i -I.git -rfakeroot
  - dcmd mv ../eid-archive*changes products/deb
  - make rpms
  - cp -a /root/rpmbuild/RPMS/noarch/* products/rpm
  artifacts:
    paths:
    - products

sign-deb:
  stage: sign
  tags:
  - repobuilder
  rules:
    - when: manual
  script:
  - set -e
  - if [ -z "$REPREPRO_BASE_DIR"]; then export REPREPRO_BASE_DIR=/srv/repo/reprepro; fi
  - ./scripts/ensure-reprepro.pl
  - for deb in products/deb/*.changes; do if ./scripts/deb-is-needed.pl $deb; then dcmd mv $deb /srv/repo/reprepro/incoming; fi; done
  - reprepro processincoming incoming
  - for deb in products/deb/*.changes; do ./scripts/deb-copy-if-needed.pl $deb; done

sign-fed:
  stage: sign
  tags:
  - repobuilder
  rules:
    - when: manual
  script:
  - set -e
  - for rpm in products/rpm/*.rpm; do ./scripts/rpm-sign-and-move.pl $rpm; done
