---
build:
  image: debian:stable
  before_script:
  - apt-get update
  - apt-get -y install --no-install-recommends devscripts equivs build-essential fakeroot rpm
  - mk-build-deps -r -i -t "apt-get -y -o Debug::pkgProblemResolver=yes --no-install-recommends"
  - mkdir -p products/deb
  - mkdir -p products/rpm
  script:
  - dpkg-buildpackage -uc -us -i -I.git -rfakeroot
  - dcmd mv ../eid-archive*changes products/deb
  - make rpms
  - cp -a /root/rpmbuild/RPMS/noarch/* products/rpm
  artifacts:
    paths:
    - products
