#!/bin/bash

set -e

CODE=$(lsb_release -c -s)
DIST=$(lsb_release -i -s)
REL=$(lsb_release -r -s)
DIR=$(mktemp -d)

too_old() {
	echo "distribution too old, cannot continue. Please upgrade, or compile from source."
	exit 1
}

case "$CODE" in
	jessie)
		:
	;;
	trusty)
		:
	;;
	qiana)
		:
	;;
	rebecca|rafaela|rosa)
		CODE=qiana
	;;
	sarah)
		:
	;;
	serena|sonya)
		CODE=sarah
	;;
	stretch)
		:
	;;
	xenial)
		:
	;;
	zesty)
		:
	;;
	*)
		echo -e "WARNING: Unsupported distribution found. Please see the website at\nhttp://eid.belgium.be/en/using_your_eid/installing_the_eid_software/linux\nfor a list of supported distributions."
		case "$DIST" in
			LinuxMint)
				if dpkg --compare-versions 18 le $REL
				then
					CODE=sarah
				else
					if dpkg --compare-versions 17 le $REL
					then
						CODE=qiana
					else
						too_old
					fi
				fi
				echo "Found Linux Mint $REL, using $CODE"
			;;
			Ubuntu)
				if dpkg --compare-versions 16.04 le $REL
				then
					CODE=xenial
				else
					if dpkg --compare-versions 14.04 le $REL
					then
						CODE=trusty
					else
						too_old
					fi
				fi
				echo "Found Ubuntu $REL, using $CODE"
			;;
			Debian)
				CODE=jessie
				if [ "$REL" = "unstable" ]; then
					CODE=stretch
				fi
				echo "Found Debian $REL, using $CODE"
			;;
			*)
				CODE=trusty
				echo "Unknown distribution found. Using trusty as fallback."
			;;
		esac
	;;
esac
sed -e "s/@DIST@/${CODE}/g" /usr/share/eid-archive/eid.list > $DIR/eid.list
ucf $DIR/eid.list /etc/apt/sources.list.d/eid.list

ln -sf /usr/share/eid-archive/keys/6773d225.gpg /etc/apt/trusted.gpg.d/eid-archive-released-builds.gpg
if grep -E '^[[:space:]]*deb.*(continuous|candidate)' /etc/apt/sources.list.d/eid.list >/dev/null 2>&1
then
	ln -sf /usr/share/eid-archive/keys/10a04d46.gpg /etc/apt/trusted.gpg.d/eid-archive-test-builds.gpg
else
	rm -f /etc/apt/trusted.gpg.d/eid-archive-test-builds.gpg
fi

if [ -x /usr/sbin/update-software-center ]; then
	update-software-center --triggered=TRIGGERED
fi

echo -e "Repository enabled, keys installed. Please run \"apt-get update\" followed by\n\"apt-get install eid-mw eid-viewer\" to install the middleware and the viewer, respectively."

#DEBHELPER#
