#!/bin/bash

set -e

CODE=$(lsb_release -c -s)
DIST=$(lsb_release -i -s)
REL=$(lsb_release -r -s)
DIR=$(mktemp -d)

too_old() {
	echo "distribution too old, cannot continue. Please upgrade, or compile from source."
	exit 1
}

case "$CODE" in
	tessa|tina|tricia)
		CODE=tara
	;;
	ulyssa)
		CODE=ulyana
	;;
	buster|sarah|tara|stretch|bionic|focal|ulyana|hirsute)
		:
	;;
	*)
		echo -e "WARNING: Unsupported distribution found. Please see the website at\nhttps://eid.belgium.be/en/faq/which-linux-distributions-are-supported#7406\nfor a list of supported distributions."
		case "$DIST" in
			LinuxMint)
				if dpkg --compare-versions 19 le $REL
				then
					CODE=tara
				else
					too_old
				fi
				echo "Found Linux Mint $REL, using $CODE"
			;;
			Ubuntu)
				if dpkg --compare-versions 18.04 le $REL
				then
					CODE=bionic
				else
					too_old
				fi
				echo "Found Ubuntu $REL, using $CODE"
			;;
			Debian)
				CODE=stretch
				if [ "$REL" = "unstable" -o "$REL" = "testing" ]; then
					CODE=buster
				fi
				echo "Found Debian $REL, using $CODE"
			;;
			*)
				CODE=xenial
				echo "Unknown distribution found. Using $CODE as fallback."
			;;
		esac
	;;
esac
sed -e "s/@DIST@/${CODE}/g" /usr/share/eid-archive/eid.list > $DIR/eid.list
ucf $DIR/eid.list /etc/apt/sources.list.d/eid.list

ln -sf /usr/share/eid-archive/keys/6773d225.gpg /etc/apt/trusted.gpg.d/eid-archive-released-builds.gpg
if grep -E '^[[:space:]]*deb.*(continuous|candidate)' /etc/apt/sources.list.d/eid.list >/dev/null 2>&1
then
	ln -sf /usr/share/eid-archive/keys/10a04d46.gpg /etc/apt/trusted.gpg.d/eid-archive-test-builds.gpg
else
	rm -f /etc/apt/trusted.gpg.d/eid-archive-test-builds.gpg
fi

if [ -x /usr/sbin/update-software-center ]; then
	update-software-center --triggered=TRIGGERED
fi

echo -e "Repository enabled, keys installed. Please run \"apt-get update\" followed by\n\"apt-get install eid-mw eid-viewer\" to install the middleware and the viewer, respectively."

#DEBHELPER#
